site_name: Rosetta Docs
site_url: https://wout.github.io/rosetta/
repo_url: https://github.com/wout/rosetta
edit_uri: https://github.com/wout/rosetta/tree/docs/docs

nav:
  - Why Rosetta?: why_rosetta.md
  - Getting started: getting_started.md
  - Setup: setup.md
  - Configuration: configuration.md
  - Locale files: locale_files.md
  - Set the current locale: set_the_current_locale.md
  - Translations: translations.md
  - Interpolation: interpolation.md
  - Pluralization: pluralization.md
  - Date, time and numbers: localization.md
  - Parser checks: parser_checks.md

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    accent: cyan
    primary: cyan
    toggle:
      icon: material/toggle-switch-off-outline
      name: Use dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    accent: cyan
    primary: cyan
    toggle:
      icon: material/toggle-switch
      name: Use light mode
  logo: assets/rosetta-logo-light.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css